# Generated by Django 3.1.5 on 2021-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_is_news',
            field=models.CharField(choices=[('N', 'Новость'), ('A', 'Статья')], default='N', max_length=1),
        ),
    ]
