# Generated by Django 3.1.5 on 2021-01-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210127_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='uname',
        ),
    ]
