# Generated by Django 3.1.5 on 2021-01-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210127_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='uname',
            new_name='username',
        ),
    ]
